from pathlib import Path
from cambc import Environment, Position
import cambc_pb2


MAPS_DIR = Path("maps")
OUTPUT_FILE = Path("known_maps.py")


def load_map26(filename):
    game_map = cambc_pb2.Map()

    with open(filename, "rb") as f:
        game_map.ParseFromString(f.read())

    width = game_map.width
    height = game_map.height

    grid = [
        [Environment.EMPTY for _ in range(width)]
        for _ in range(height)
    ]

    for y, row in enumerate(game_map.rows):
        for x, tile in enumerate(row.tiles):
            if tile == 0:
                grid[y][x] = Environment.EMPTY
            elif tile == 1:
                grid[y][x] = Environment.WALL
            elif tile == 2:
                grid[y][x] = Environment.ORE_TITANIUM
            elif tile == 3:
                grid[y][x] = Environment.ORE_AXIONITE
            else:
                raise ValueError(f"Unknown tile value {tile} at ({x}, {y})")

    spawn_positions = [
        Position(core.position.x, core.position.y)
        for core in game_map.cores
    ]

    return grid, spawn_positions, height, width


def tile_to_code(tile):
    if tile == Environment.EMPTY:
        return "Environment.EMPTY"
    elif tile == Environment.WALL:
        return "Environment.WALL"
    elif tile == Environment.ORE_TITANIUM:
        return "Environment.ORE_TITANIUM"
    elif tile == Environment.ORE_AXIONITE:
        return "Environment.ORE_AXIONITE"
    else:
        raise ValueError(f"Unknown Environment tile: {tile}")


def grid_to_python(grid):
    lines = ["["]
    for row in grid:
        row_text = ", ".join(tile_to_code(tile) for tile in row)
        lines.append(f"        [{row_text}],")
    lines.append("    ]")
    return "\n".join(lines)


def spawns_to_python(spawns):
    inner = ", ".join(
        f"Position({p.x}, {p.y})"
        for p in spawns
    )
    return f"[{inner}]"


def generate_known_maps():
    known_maps = {}

    for path in sorted(MAPS_DIR.glob("*.map26")):
        grid, spawns, height, width = load_map26(path)

        key = (height, width)

        entry = {
            "name": path.name,
            "spawns": spawns,
            "grid": grid,
        }

        known_maps.setdefault(key, []).append(entry)

    return known_maps


def write_output(known_maps):
    lines = []
    lines.append("from cambc import Environment, Position")
    lines.append("")
    lines.append("# Auto-generated by load_maps.py")
    lines.append("# Do not edit manually.")
    lines.append("")
    lines.append("KNOWN_MAPS = {")

    for (height, width), maps in sorted(known_maps.items()):
        lines.append(f"    ({height}, {width}): [")

        for m in maps:
            lines.append("        {")
            lines.append(f"            'name': {m['name']!r},")
            lines.append(f"            'spawns': {spawns_to_python(m['spawns'])},")
            lines.append("            'grid': " + grid_to_python(m["grid"]) + ",")
            lines.append("        },")

        lines.append("    ],")

    lines.append("}")
    lines.append("")

    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")


def main():
    known_maps = generate_known_maps()
    write_output(known_maps)

    total = sum(len(v) for v in known_maps.values())
    print(f"Wrote {OUTPUT_FILE}")
    print(f"{total} maps across {len(known_maps)} dimension groups")


if __name__ == "__main__":
    main()