from pathlib import Path
from cambc import Position
import cambc_pb2


MAPS_DIR = Path("maps")
OUTPUT_FILES = (
    Path("bots/Lethe/known_maps.py"),
)


def load_map26(filename):
    game_map = cambc_pb2.Map()

    with open(filename, "rb") as f:
        game_map.ParseFromString(f.read())

    width = game_map.width
    height = game_map.height

    env_masks = [0, 0, 0, 0]

    for y, row in enumerate(game_map.rows):
        for x, tile in enumerate(row.tiles):
            if tile not in (0, 1, 2, 3):
                raise ValueError(f"Unknown tile value {tile} at ({x}, {y})")
            env_masks[tile] |= 1 << (x + y * width)

    spawn_positions = [
        Position(core.position.x, core.position.y)
        for core in game_map.cores
    ]

    return env_masks, spawn_positions, height, width


def _tile_env_at(env_masks, width, x, y):
    bit = 1 << (x + y * width)
    for env_idx, mask in enumerate(env_masks):
        if mask & bit:
            return env_idx
    raise ValueError(f"No environment found at ({x}, {y})")


def _is_symmetric(env_masks, spawns, width, height, transform):
    spawn_set = {(p.x, p.y) for p in spawns}

    for y in range(height):
        for x in range(width):
            tx, ty = transform(x, y)
            if _tile_env_at(env_masks, width, x, y) != _tile_env_at(env_masks, width, tx, ty):
                return False

    transformed_spawns = {transform(p.x, p.y) for p in spawns}
    return transformed_spawns == spawn_set


def determine_symmetries(env_masks, spawns, width, height):
    return {
        "hor_sym": _is_symmetric(
            env_masks,
            spawns,
            width,
            height,
            lambda x, y: (width - 1 - x, y),
        ),
        "ver_sym": _is_symmetric(
            env_masks,
            spawns,
            width,
            height,
            lambda x, y: (x, height - 1 - y),
        ),
        "rot_sym": _is_symmetric(
            env_masks,
            spawns,
            width,
            height,
            lambda x, y: (width - 1 - x, height - 1 - y),
        ),
    }


def env_masks_to_python(env_masks):
    inner = ", ".join(str(mask) for mask in env_masks)
    return f"[{inner}]"


def spawns_to_python(spawns):
    inner = ", ".join(
        f"Position({p.x}, {p.y})"
        for p in spawns
    )
    return f"[{inner}]"


def generate_known_maps():
    known_maps = {}

    for path in sorted(MAPS_DIR.glob("*.map26")):
        env_masks, spawns, height, width = load_map26(path)
        symmetries = determine_symmetries(env_masks, spawns, width, height)

        key = (height, width)

        entry = {
            "name": path.name,
            "spawns": spawns,
            "env_masks": env_masks,
            **symmetries,
        }

        known_maps.setdefault(key, []).append(entry)

    return known_maps


def write_output(known_maps):
    lines = []
    lines.append("from cambc import Position")
    lines.append("")
    lines.append("# Auto-generated by load_maps_bitmask.py")
    lines.append("# Do not edit manually.")
    lines.append("")
    lines.append("KNOWN_MAPS = {")

    for (height, width), maps in sorted(known_maps.items()):
        lines.append(f"    ({height}, {width}): [")

        for m in maps:
            lines.append("        {")
            lines.append(f"            'name': {m['name']!r},")
            lines.append(f"            'spawns': {spawns_to_python(m['spawns'])},")
            lines.append(f"            'env_masks': {env_masks_to_python(m['env_masks'])},")
            lines.append(f"            'hor_sym': {m['hor_sym']},")
            lines.append(f"            'ver_sym': {m['ver_sym']},")
            lines.append(f"            'rot_sym': {m['rot_sym']},")
            lines.append("        },")

        lines.append("    ],")

    lines.append("}")
    lines.append("")

    output = "\n".join(lines)
    for output_file in OUTPUT_FILES:
        output_file.write_text(output, encoding="utf-8")


def main():
    known_maps = generate_known_maps()
    write_output(known_maps)

    total = sum(len(v) for v in known_maps.values())
    print("Wrote:")
    for output_file in OUTPUT_FILES:
        print(f"  {output_file}")
    print(f"{total} maps across {len(known_maps)} dimension groups")


if __name__ == "__main__":
    main()
