# builder_1.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 2:
        pos = Position(6, 6)
        target = Position(6, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 3:
        pos = Position(6, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 4:
        pos = Position(5, 5)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 5:
        pos = Position(4, 4)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 6:
        pos = Position(4, 6)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 7:
        pos = Position(4, 5)
        target = Position(6, 6)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 8:
        pos = Position(3, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 9:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 10:
        pos = Position(6, 7)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 11:
        pos = Position(5, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 12:
        pos = Position(4, 9)
        target = Position(7, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 13:
        pos = Position(3, 9)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 14:
        pos = Position(2, 9)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 15:
        pos = Position(2, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 16:
        pos = Position(2, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 17:
        pos = Position(1, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 18:
        pos = Position(2, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 19:
        pass
        return
    if turn == 20:
        pos = Position(3, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 21:
        pos = Position(2, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 22:
        pos = Position(3, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 23:
        pos = Position(4, 11)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        return
    if turn == 24:
        pos = Position(4, 12)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 25:
        pos = Position(4, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 26:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 27:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(4, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 28:
        pos = Position(3, 8)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 29:
        pos = Position(5, 7)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 30:
        pos = Position(4, 7)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 31:
        pos = Position(3, 7)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 32:
        pos = Position(3, 9)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(3, 9)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 33:
        pos = Position(3, 6)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 34:
        pos = Position(2, 6)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 35:
        pos = Position(2, 7)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 36:
        pos = Position(2, 5)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 37:
        pos = Position(2, 4)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 38:
        pos = Position(2, 5)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(2, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 39:
        pos = Position(2, 3)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 40:
        pos = Position(2, 4)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(3, 3)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 41:
        pos = Position(3, 2)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 42:
        pos = Position(4, 3)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        pos = Position(2, 3)
        if c.can_destroy(pos):
            c.destroy(pos)
        return
    if turn == 43:
        pos = Position(4, 2)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 44:
        pos = Position(5, 2)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 45:
        pos = Position(5, 3)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 46:
        pos = Position(5, 4)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 47:
        pos = Position(6, 3)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 48:
        pos = Position(7, 3)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 49:
        pos = Position(7, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 50:
        pos = Position(7, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 51:
        pos = Position(8, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 52:
        pos = Position(9, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 53:
        pos = Position(10, 4)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 54:
        pos = Position(10, 5)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 55:
        pos = Position(10, 6)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 56:
        pos = Position(10, 7)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 57:
        pos = Position(10, 8)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 58:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 59:
        pos = Position(7, 10)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 60:
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(5, 10)
        target = Position(7, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    if turn == 61:
        pos = Position(5, 11)
        direction = Direction.WEST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 62:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(3, 13)
        if c.can_build_road(pos):
            c.build_road(pos)
        return
    if turn == 63:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(4, 14)
        if c.can_build_road(pos):
            c.build_road(pos)
        return
    if turn == 64:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(5, 14)
        target = Position(5, 11)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    if turn == 65:
        pos = Position(5, 15)
        direction = Direction.EAST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 66:
        pos = Position(5, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 67:
        pos = Position(4, 16)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 68:
        pos = Position(4, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 69:
        pos = Position(3, 17)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 70:
        pos = Position(2, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 71:
        pos = Position(2, 16)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 72:
        pos = Position(1, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 73:
        pos = Position(3, 15)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 74:
        pos = Position(4, 15)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 75:
        pos = Position(3, 16)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 76:
        pos = Position(3, 18)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 77:
        pos = Position(3, 19)
        target = Position(3, 16)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 78:
        pos = Position(3, 20)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 79:
        pos = Position(2, 20)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 80:
        pos = Position(2, 21)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 81:
        pos = Position(1, 20)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 82:
        pos = Position(2, 19)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 83:
        pos = Position(4, 19)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 84:
        pos = Position(4, 20)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 85:
        pos = Position(4, 21)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 86:
        c.self_destruct()
        return
    return
