# builder_1.py
# AUTO-GENERATED by bc_selfplay_ui.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 2:
        pos = Position(8, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 3:
        pos = Position(8, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 4:
        pos = Position(8, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 5:
        pos = Position(8, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 6:
        pos = Position(7, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 7:
        pass
        return
    if turn == 8:
        pass
        return
    if turn == 9:
        pass
        return
    if turn == 10:
        pass
        return
    if turn == 11:
        pass
        return
    if turn == 12:
        pass
        return
    if turn == 13:
        pass
        return
    if turn == 14:
        pass
        return
    if turn == 15:
        pass
        return
    if turn == 16:
        pass
        return
    if turn == 17:
        pass
        return
    if turn == 18:
        pass
        return
    if turn == 19:
        pass
        return
    if turn == 20:
        pass
        return
    if turn == 21:
        pass
        return
    if turn == 22:
        pass
        return
    if turn == 23:
        pass
        return
    if turn == 24:
        pass
        return
    if turn == 25:
        pass
        return
    if turn == 26:
        pass
        return
    if turn == 27:
        pass
        return
    if turn == 28:
        pass
        return
    if turn == 29:
        pass
        return
    if turn == 30:
        pass
        return
    if turn == 31:
        pass
        return
    if turn == 32:
        pass
        return
    if turn == 33:
        pass
        return
    if turn == 34:
        pos = Position(9, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 35:
        pass
        return
    if turn == 36:
        pass
        return
    if turn == 37:
        pass
        return
    if turn == 38:
        pass
        return
    if turn == 39:
        pass
        return
    if turn == 40:
        pass
        return
    if turn == 41:
        pass
        return
    if turn == 42:
        pass
        return
    if turn == 43:
        pass
        return
    if turn == 44:
        pass
        return
    if turn == 45:
        pass
        return
    if turn == 46:
        pass
        return
    if turn == 47:
        pass
        return
    if turn == 48:
        pass
        return
    if turn == 49:
        pass
        return
    if turn == 50:
        pass
        return
    if turn == 51:
        pass
        return
    if turn == 52:
        pass
        return
    if turn == 53:
        pass
        return
    if turn == 54:
        pass
        return
    if turn == 55:
        pass
        return
    if turn == 56:
        pass
        return
    if turn == 57:
        pass
        return
    if turn == 58:
        pass
        return
    if turn == 59:
        pass
        return
    if turn == 60:
        pass
        return
    if turn == 61:
        pass
        return
    if turn == 62:
        pass
        return
    if turn == 63:
        pass
        return
    if turn == 64:
        pass
        return
    if turn == 65:
        pass
        return
    if turn == 66:
        pass
        return
    if turn == 67:
        pass
        return
    if turn == 68:
        pass
        return
    if turn == 69:
        pass
        return
    if turn == 70:
        pass
        return
    if turn == 71:
        pass
        return
    if turn == 72:
        pass
        return
    if turn == 73:
        pass
        return
    if turn == 74:
        pass
        return
    if turn == 75:
        pass
        return
    if turn == 76:
        pass
        return
    if turn == 77:
        pass
        return
    if turn == 78:
        pass
        return
    if turn == 79:
        pass
        return
    if turn == 80:
        pass
        return
    if turn == 81:
        pass
        return
    if turn == 82:
        pass
        return
    if turn == 83:
        pass
        return
    if turn == 84:
        pass
        return
    if turn == 85:
        pass
        return
    if turn == 86:
        pass
        return
    if turn == 215:
        pass
        return
    return
