# builder_2.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 2:
        pos = Position(6, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 3:
        pos = Position(6, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 4:
        pos = Position(5, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 5:
        pos = Position(7, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 6:
        pos = Position(6, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 7:
        pos = Position(6, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 8:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(6, 9)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 9:
        pos = Position(7, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 10:
        pos = Position(8, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 11:
        pos = Position(8, 12)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 12:
        pos = Position(8, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 13:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(5, 11)
        direction = Direction.WEST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        return
    if turn == 14:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(6, 8)
        if c.can_build_road(pos):
            c.build_road(pos)
        return
    if turn == 15:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 16:
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(4, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 17:
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(3, 8)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 18:
        pos = Position(3, 7)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 19:
        pos = Position(2, 7)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 20:
        pos = Position(2, 6)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 21:
        pass
        return
    if turn == 22:
        pass
        return
    if turn == 23:
        pass
        return
    if turn == 24:
        pos = Position(5, 7)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 25:
        pos = Position(4, 7)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 26:
        pass
        return
    if turn == 27:
        pos = Position(3, 6)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 28:
        pass
        return
    if turn == 29:
        pass
        return
    if turn == 30:
        pos = Position(3, 9)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(3, 9)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 31:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(2, 5)
        if c.can_build_road(pos):
            c.build_road(pos)
        return
    if turn == 32:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(3, 4)
        if c.can_build_road(pos):
            c.build_road(pos)
        return
    if turn == 33:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(2, 5)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(2, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 34:
        pass
        return
    if turn == 35:
        pass
        return
    if turn == 36:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 37:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 38:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 39:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 40:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 41:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 42:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 43:
        pos = Position(5, 10)
        target = Position(7, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 44:
        pos = Position(5, 13)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 45:
        pass
        return
    if turn == 46:
        pass
        return
    if turn == 47:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 48:
        pos = Position(5, 14)
        target = Position(5, 11)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 49:
        pass
        return
    if turn == 50:
        pos = Position(3, 16)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 51:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 52:
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 53:
        pos = Position(2, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 54:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 55:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 56:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 57:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 58:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 59:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 60:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 61:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 62:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 63:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 64:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 65:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(3, 3)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 66:
        pos = Position(4, 3)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 67:
        pos = Position(4, 2)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 68:
        pos = Position(3, 2)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 69:
        pos = Position(4, 3)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(5, 3)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 70:
        pos = Position(4, 3)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 71:
        pos = Position(5, 2)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 72:
        pos = Position(5, 4)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 73:
        pos = Position(6, 3)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 74:
        pos = Position(7, 3)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 75:
        pos = Position(7, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 76:
        pos = Position(7, 5)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 77:
        pos = Position(8, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 78:
        pos = Position(9, 4)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 79:
        pos = Position(10, 4)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 80:
        pos = Position(10, 5)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 81:
        pos = Position(10, 6)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 82:
        pos = Position(10, 7)
        direction = Direction.SOUTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 83:
        pos = Position(11, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 84:
        pos = Position(10, 8)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 85:
        pos = Position(12, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 86:
        pass
        return
    if turn == 87:
        pass
        return
    if turn == 88:
        pass
        return
    if turn == 89:
        pos = Position(12, 9)
        target = Position(9, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    if turn == 90:
        pass
        return
    if turn == 91:
        pos = Position(11, 9)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    return
