# builder_35.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 35:
        pos = Position(9, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 36:
        pos = Position(10, 10)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 37:
        pos = Position(10, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 38:
        pos = Position(10, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 39:
        pos = Position(9, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 40:
        pos = Position(10, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 41:
        pos = Position(11, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 42:
        pass
        return
    if turn == 43:
        pass
        return
    if turn == 44:
        pass
        return
    if turn == 45:
        pos = Position(11, 13)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 46:
        pos = Position(11, 14)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 47:
        pos = Position(11, 15)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 48:
        pass
        return
    if turn == 49:
        pass
        return
    if turn == 50:
        pass
        return
    if turn == 51:
        pos = Position(11, 16)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 52:
        pos = Position(10, 16)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 53:
        pos = Position(9, 16)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 54:
        pass
        return
    if turn == 55:
        pos = Position(8, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 56:
        pos = Position(9, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 57:
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(11, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 58:
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(12, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 59:
        pos = Position(10, 15)
        target = Position(10, 12)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 60:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(12, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 61:
        pos = Position(11, 13)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(11, 13)
        target = Position(10, 12)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 62:
        pass
        return
    if turn == 63:
        pos = Position(10, 12)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(10, 12)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 64:
        pos = Position(12, 12)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 65:
        pos = Position(13, 11)
        direction = Direction.WEST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 66:
        pos = Position(13, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 67:
        pos = Position(14, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 68:
        pos = Position(14, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 69:
        pos = Position(15, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 70:
        pos = Position(14, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 71:
        pos = Position(14, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 72:
        pos = Position(14, 9)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 73:
        pos = Position(14, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 74:
        pos = Position(13, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 75:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(15, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 76:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 77:
        pass
        return
    if turn == 78:
        pos = Position(16, 12)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 79:
        pos = Position(16, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 80:
        pos = Position(16, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 81:
        pos = Position(17, 11)
        direction = Direction.EAST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 82:
        pos = Position(17, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 83:
        pos = Position(17, 9)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 84:
        pos = Position(16, 9)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 85:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 86:
        pass
        return
    if turn == 87:
        pass
        return
    if turn == 88:
        pass
        return
    if turn == 89:
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 90:
        pos = Position(15, 9)
        target = Position(12, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    return
