# builder_2.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 3:
        pos = Position(6, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 4:
        pos = Position(6, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 5:
        pos = Position(5, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 6:
        pos = Position(7, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 7:
        pos = Position(6, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 8:
        pos = Position(6, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 9:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(6, 9)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 10:
        pos = Position(7, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 11:
        pos = Position(8, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 12:
        pos = Position(8, 12)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 13:
        pos = Position(8, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 14:
        pos = Position(9, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 15:
        pos = Position(10, 10)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 16:
        pos = Position(10, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 17:
        pos = Position(10, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 18:
        pos = Position(9, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 19:
        pass
        return
    if turn == 20:
        pass
        return
    if turn == 21:
        pass
        return
    if turn == 22:
        pass
        return
    if turn == 23:
        pass
        return
    if turn == 24:
        pos = Position(10, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 25:
        pass
        return
    if turn == 26:
        pass
        return
    if turn == 27:
        pos = Position(11, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 28:
        pass
        return
    if turn == 29:
        pass
        return
    if turn == 30:
        pass
        return
    if turn == 31:
        pass
        return
    if turn == 32:
        pass
        return
    if turn == 33:
        pass
        return
    if turn == 34:
        pass
        return
    if turn == 35:
        pos = Position(11, 13)
        target = Position(10, 12)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    if turn == 36:
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(12, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 37:
        pos = Position(10, 14)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 38:
        pos = Position(10, 15)
        target = Position(10, 12)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 39:
        pos = Position(9, 15)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 40:
        pos = Position(8, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 41:
        pos = Position(9, 16)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 42:
        pass
        return
    if turn == 43:
        pos = Position(9, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 44:
        pos = Position(11, 15)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 45:
        pos = Position(12, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 46:
        pos = Position(11, 16)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 47:
        pos = Position(11, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 48:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 49:
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        pos = Position(10, 12)
        if c.can_destroy(pos):
            c.destroy(pos)
        pos = Position(10, 12)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 50:
        pos = Position(12, 12)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 51:
        pos = Position(13, 11)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 52:
        pos = Position(13, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 53:
        pos = Position(14, 12)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 54:
        pos = Position(14, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 55:
        pos = Position(15, 12)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 56:
        pos = Position(14, 11)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 57:
        pos = Position(14, 10)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 58:
        pos = Position(14, 9)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 59:
        pos = Position(14, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 60:
        pos = Position(13, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 61:
        pos = Position(12, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 62:
        pos = Position(11, 8)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.EAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 63:
        pos = Position(12, 9)
        target = Position(9, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 64:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(15, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 65:
        pos = Position(15, 9)
        target = Position(12, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 66:
        pos = Position(16, 12)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 67:
        pos = Position(16, 13)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 68:
        pos = Position(17, 11)
        direction = Direction.EAST
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 69:
        pos = Position(17, 10)
        target = Position(15, 9)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 70:
        pos = Position(16, 11)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 71:
        pos = Position(17, 13)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 72:
        pos = Position(17, 14)
        target = Position(17, 11)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 73:
        pos = Position(17, 15)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 74:
        pos = Position(16, 16)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 75:
        pos = Position(15, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 76:
        pos = Position(16, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 77:
        pos = Position(18, 16)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 78:
        pos = Position(19, 16)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 79:
        pos = Position(18, 17)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 80:
        pos = Position(17, 17)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 81:
        pos = Position(17, 18)
        if c.can_build_road(pos):
            c.build_road(pos)
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 82:
        direction = Direction.NORTH
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 83:
        pos = Position(17, 16)
        if c.can_build_foundry(pos):
            c.build_foundry(pos)
        return
    if turn == 84:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(17, 19)
        target = Position(17, 16)
        if c.can_build_bridge(pos, target):
            c.build_bridge(pos, target)
        return
    if turn == 85:
        direction = Direction.SOUTH
        if c.can_move(direction):
            c.move(direction)
        pos = Position(16, 20)
        direction = Direction.NORTH
        if c.can_build_splitter(pos, direction):
            c.build_splitter(pos, direction)
        return
    if turn == 86:
        pos = Position(17, 20)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.SOUTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 87:
        pos = Position(16, 21)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 88:
        pos = Position(16, 19)
        direction = Direction.EAST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        return
    if turn == 89:
        pos = Position(18, 20)
        direction = Direction.NORTH
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.SOUTHEAST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 90:
        pos = Position(18, 21)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        return
    if turn == 91:
        pos = Position(19, 20)
        if c.can_build_harvester(pos):
            c.build_harvester(pos)
        direction = Direction.NORTHWEST
        if c.can_move(direction):
            c.move(direction)
        return
    if turn == 92:
        pos = Position(18, 19)
        direction = Direction.WEST
        if c.can_build_conveyor(pos, direction):
            c.build_conveyor(pos, direction)
        direction = Direction.WEST
        if c.can_move(direction):
            c.move(direction)
        return
    return
