# core.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 0:
        pos = Position(7, 7)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 1:
        pos = Position(7, 9)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 11:
        amount = 7
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 12:
        amount = 12
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 13:
        amount = 6
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 14:
        amount = 3
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 15:
        amount = 2
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 16:
        amount = 13
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 17:
        amount = 4
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 18:
        amount = 4
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 19:
        amount = 16
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 20:
        amount = 13
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 21:
        amount = 5
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 22:
        amount = 14
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 23:
        amount = 5
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 24:
        amount = 11
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 25:
        amount = 15
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 27:
        amount = 11
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 30:
        amount = 29
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 31:
        amount = 1
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 32:
        amount = 1
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 33:
        amount = 37
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 34:
        amount = 29
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        pos = Position(9, 9)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 35:
        amount = 6
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 36:
        amount = 20
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 37:
        amount = 3
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 38:
        amount = 9
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 39:
        amount = 42
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 40:
        amount = 19
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 41:
        amount = 22
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 42:
        amount = 3
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 43:
        amount = 25
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 44:
        amount = 19
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 45:
        amount = 21
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 46:
        amount = 21
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 47:
        amount = 24
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 48:
        amount = 18
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 49:
        amount = 1
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 50:
        amount = 46
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 51:
        amount = 8
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 52:
        amount = 26
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 53:
        amount = 29
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 55:
        amount = 28
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 56:
        amount = 26
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 57:
        amount = 25
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 58:
        amount = 30
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 59:
        amount = 29
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 60:
        amount = 28
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 61:
        amount = 28
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 62:
        amount = 2
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 63:
        amount = 64
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 64:
        amount = 1
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 65:
        amount = 43
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 66:
        amount = 42
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 67:
        amount = 14
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 68:
        amount = 37
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 69:
        amount = 44
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 70:
        amount = 43
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 71:
        amount = 10
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 72:
        amount = 72
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 73:
        amount = 10
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 74:
        amount = 45
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 75:
        amount = 46
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 76:
        amount = 69
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 77:
        amount = 42
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 78:
        amount = 16
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 79:
        amount = 17
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 80:
        amount = 45
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 81:
        amount = 54
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 82:
        amount = 49
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 83:
        amount = 16
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 84:
        amount = 80
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 85:
        amount = 12
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 86:
        amount = 41
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 87:
        amount = 41
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 88:
        amount = 38
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 89:
        amount = 42
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 90:
        amount = 42
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    if turn == 91:
        amount = 93
        ti, ax = c.get_global_resources()
        if ax >= amount:
            c.convert(amount)
        return
    return
