# core.py
# AUTO-GENERATED by bc_selfplay_ui.py. Manual edits may be overwritten.

from cambc import *


def run(c: Controller) -> None:
    turn = c.get_current_round()
    if turn == 1:
        pos = Position(8, 9)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 2:
        pos = Position(7, 9)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 3:
        pos = Position(9, 9)
        if c.can_spawn(pos):
            c.spawn_builder(pos)
        return
    if turn == 4:
        pass
        return
    if turn == 5:
        pass
        return
    if turn == 6:
        pass
        return
    if turn == 7:
        pass
        return
    if turn == 8:
        pass
        return
    if turn == 9:
        pass
        return
    if turn == 10:
        pass
        return
    if turn == 11:
        pass
        return
    if turn == 12:
        pass
        return
    if turn == 13:
        pass
        return
    if turn == 14:
        pass
        return
    if turn == 15:
        pass
        return
    if turn == 16:
        pass
        return
    if turn == 17:
        pass
        return
    if turn == 18:
        pass
        return
    if turn == 19:
        pass
        return
    if turn == 20:
        pass
        return
    if turn == 21:
        pass
        return
    if turn == 22:
        pass
        return
    if turn == 23:
        pass
        return
    if turn == 24:
        pass
        return
    if turn == 25:
        pass
        return
    if turn == 26:
        pass
        return
    if turn == 27:
        pass
        return
    if turn == 28:
        pass
        return
    if turn == 29:
        pass
        return
    if turn == 30:
        pass
        return
    if turn == 31:
        pass
        return
    if turn == 32:
        pass
        return
    if turn == 33:
        pass
        return
    if turn == 34:
        pass
        return
    if turn == 35:
        pass
        return
    if turn == 36:
        pass
        return
    if turn == 37:
        pass
        return
    if turn == 38:
        pass
        return
    if turn == 39:
        pass
        return
    if turn == 40:
        pass
        return
    if turn == 41:
        pass
        return
    if turn == 42:
        pass
        return
    if turn == 43:
        pass
        return
    if turn == 44:
        pass
        return
    if turn == 45:
        pass
        return
    if turn == 46:
        pass
        return
    if turn == 47:
        pass
        return
    if turn == 48:
        pass
        return
    if turn == 49:
        pass
        return
    if turn == 50:
        pass
        return
    if turn == 51:
        pass
        return
    if turn == 52:
        pass
        return
    if turn == 53:
        pass
        return
    if turn == 54:
        pass
        return
    if turn == 55:
        pass
        return
    if turn == 56:
        pass
        return
    if turn == 57:
        pass
        return
    if turn == 58:
        pass
        return
    if turn == 59:
        pass
        return
    if turn == 60:
        pass
        return
    if turn == 61:
        pass
        return
    if turn == 62:
        pass
        return
    if turn == 63:
        pass
        return
    if turn == 64:
        pass
        return
    if turn == 65:
        pass
        return
    if turn == 66:
        pass
        return
    if turn == 67:
        pass
        return
    if turn == 68:
        pass
        return
    if turn == 69:
        pass
        return
    if turn == 70:
        pass
        return
    if turn == 71:
        pass
        return
    if turn == 72:
        pass
        return
    if turn == 73:
        pass
        return
    if turn == 74:
        pass
        return
    if turn == 75:
        pass
        return
    if turn == 76:
        pass
        return
    if turn == 77:
        pass
        return
    if turn == 78:
        pass
        return
    if turn == 79:
        pass
        return
    if turn == 80:
        pass
        return
    if turn == 81:
        pass
        return
    if turn == 82:
        pass
        return
    if turn == 83:
        pass
        return
    if turn == 84:
        pass
        return
    if turn == 85:
        pass
        return
    if turn == 86:
        pass
        return
    if turn == 87:
        pass
        return
    if turn == 88:
        pass
        return
    if turn == 89:
        pass
        return
    if turn == 90:
        pass
        return
    if turn == 91:
        pass
        return
    if turn == 92:
        pass
        return
    if turn == 93:
        pass
        return
    if turn == 94:
        pass
        return
    if turn == 95:
        pass
        return
    if turn == 96:
        pass
        return
    if turn == 97:
        pass
        return
    if turn == 98:
        pass
        return
    if turn == 99:
        pass
        return
    if turn == 100:
        pass
        return
    if turn == 101:
        pass
        return
    if turn == 102:
        pass
        return
    if turn == 103:
        pass
        return
    if turn == 104:
        pass
        return
    if turn == 105:
        pass
        return
    if turn == 106:
        pass
        return
    if turn == 107:
        pass
        return
    if turn == 108:
        pass
        return
    if turn == 109:
        pass
        return
    if turn == 110:
        pass
        return
    if turn == 111:
        pass
        return
    if turn == 112:
        pass
        return
    if turn == 113:
        pass
        return
    if turn == 114:
        pass
        return
    if turn == 115:
        pass
        return
    if turn == 116:
        pass
        return
    if turn == 117:
        pass
        return
    if turn == 118:
        pass
        return
    if turn == 119:
        pass
        return
    if turn == 120:
        pass
        return
    if turn == 121:
        pass
        return
    if turn == 122:
        pass
        return
    if turn == 123:
        pass
        return
    if turn == 124:
        pass
        return
    if turn == 125:
        pass
        return
    if turn == 126:
        pass
        return
    if turn == 127:
        pass
        return
    if turn == 128:
        pass
        return
    if turn == 129:
        pass
        return
    if turn == 130:
        pass
        return
    if turn == 131:
        pass
        return
    if turn == 132:
        pass
        return
    if turn == 133:
        pass
        return
    if turn == 134:
        pass
        return
    if turn == 135:
        pass
        return
    if turn == 136:
        pass
        return
    if turn == 137:
        pass
        return
    if turn == 138:
        pass
        return
    if turn == 139:
        pass
        return
    if turn == 140:
        pass
        return
    if turn == 141:
        pass
        return
    if turn == 142:
        pass
        return
    if turn == 143:
        pass
        return
    if turn == 144:
        pass
        return
    if turn == 145:
        pass
        return
    if turn == 146:
        pass
        return
    if turn == 147:
        pass
        return
    if turn == 148:
        pass
        return
    if turn == 149:
        pass
        return
    if turn == 150:
        pass
        return
    if turn == 151:
        pass
        return
    if turn == 152:
        pass
        return
    if turn == 153:
        pass
        return
    if turn == 154:
        pass
        return
    if turn == 155:
        pass
        return
    if turn == 156:
        pass
        return
    if turn == 157:
        pass
        return
    if turn == 158:
        pass
        return
    if turn == 159:
        pass
        return
    if turn == 160:
        pass
        return
    if turn == 161:
        pass
        return
    if turn == 162:
        pass
        return
    if turn == 163:
        pass
        return
    if turn == 164:
        pass
        return
    if turn == 165:
        pass
        return
    if turn == 166:
        pass
        return
    if turn == 167:
        pass
        return
    if turn == 168:
        pass
        return
    if turn == 169:
        pass
        return
    if turn == 170:
        pass
        return
    if turn == 171:
        pass
        return
    if turn == 172:
        pass
        return
    if turn == 173:
        pass
        return
    if turn == 174:
        pass
        return
    if turn == 175:
        pass
        return
    if turn == 176:
        pass
        return
    if turn == 177:
        pass
        return
    if turn == 178:
        pass
        return
    if turn == 179:
        pass
        return
    if turn == 180:
        pass
        return
    if turn == 181:
        pass
        return
    if turn == 182:
        pass
        return
    if turn == 183:
        pass
        return
    if turn == 184:
        pass
        return
    if turn == 185:
        pass
        return
    if turn == 186:
        pass
        return
    if turn == 187:
        pass
        return
    if turn == 188:
        pass
        return
    if turn == 189:
        pass
        return
    if turn == 190:
        pass
        return
    if turn == 191:
        pass
        return
    if turn == 192:
        pass
        return
    if turn == 193:
        pass
        return
    if turn == 194:
        pass
        return
    if turn == 195:
        pass
        return
    if turn == 196:
        pass
        return
    if turn == 197:
        pass
        return
    if turn == 198:
        pass
        return
    if turn == 199:
        pass
        return
    if turn == 200:
        pass
        return
    if turn == 201:
        pass
        return
    if turn == 202:
        pass
        return
    if turn == 203:
        pass
        return
    if turn == 204:
        pass
        return
    if turn == 205:
        pass
        return
    if turn == 206:
        pass
        return
    if turn == 207:
        pass
        return
    if turn == 208:
        pass
        return
    if turn == 209:
        pass
        return
    if turn == 210:
        pass
        return
    if turn == 211:
        pass
        return
    if turn == 212:
        pass
        return
    if turn == 213:
        pass
        return
    if turn == 214:
        pass
        return
    if turn == 215:
        pass
        return
    return
