# main.py
# AUTO-GENERATED by herberts_hardcoding.py. Manual edits may be overwritten.

from cambc import Controller, EntityType
import random

import builder
import core
import builder_1


class Player:
    def __init__(self):
        self.initialized = False
        self.me = None
        self.spawn_turn = None

    def run(self, c: Controller) -> None:
        etype = c.get_entity_type()

        if not self.initialized:
            random.seed(c.get_current_round())

            if etype == EntityType.CORE:
                self.me = core
            elif etype == EntityType.BUILDER_BOT:
                # The builder's first turn is normally one round after it was spawned.
                # This matches the user's SPAWN_TURN = c.get_current_round() - 1 pattern.
                self.spawn_turn = c.get_current_round() - 1
                if self.spawn_turn == 1:
                    self.me = builder_1
                else:
                    self.me = builder
            else:
                return

            self.initialized = True

        if self.me is not None:
            self.me.run(c)
